# This workflow is for testing purpose and run on the validator according to PR description.
#
# To use this workflow, you will need to set up a .github/checklist-validator.yml
# file with configuration.  For more information, see:
# https://github.com/actions/checklist-validator

name: Validate PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check if required checkboxes are ticked
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body;

            const hasFullDeploymentChecked = body.includes('- [x] ✅ **Yes** – This is a full deployment');
            const hasFSGDashboardChecked = body.includes('- [x] FSG Dashboard deployment is included');
            const hasRestAppsChecked = body.includes('- [x] All 34 app image updates are included');

            const hasPartialDeploymentChecked = body.includes('- [x] ❌ **No** – This is **not** a full deployment');

            if (hasFullDeploymentChecked) {
              if (!hasFSGDashboardChecked || !hasRestAppsChecked) {
                core.setFailed('❌ You selected full deployment but did not complete all required sub-checks.');
              } else {
                core.info('✅ Full deployment with all sub-checks verified.');
              }
            } else if (!hasPartialDeploymentChecked) {
              core.setFailed('❌ Please select either full or partial deployment.');
            } else {
              core.info('✅ Partial deployment correctly marked.');
            }

